/* automatically generated by rust-bindgen 0.59.2 */

pub type size_t = ::libc::c_uint;
pub type wint_t = ::libc::c_int;
pub type __int32_t = ::libc::c_int;
pub type __uint32_t = ::libc::c_uint;
pub type __int64_t = ::libc::c_longlong;
pub type __uint64_t = ::libc::c_ulonglong;
pub type __int_least64_t = ::libc::c_longlong;
pub type _off_t = __int64_t;
pub type _fpos_t = __int64_t;
pub type __ino_t = __uint32_t;
pub type __dev_t = __uint32_t;
pub type __blkcnt_t = ::libc::c_long;
pub type __blksize_t = ::libc::c_long;
pub type __fsblkcnt_t = __uint64_t;
pub type __fsfilcnt_t = __uint32_t;
pub type __uid_t = ::libc::c_ushort;
pub type __gid_t = ::libc::c_ushort;
pub type __mode_t = __uint32_t;
pub type __off_t = _off_t;
pub type _ssize_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _mbstate_t {
    pub __count: ::libc::c_int,
    pub __value: _mbstate_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _mbstate_t__bindgen_ty_1 {
    pub __wch: wint_t,
    pub __wchb: [::libc::c_uchar; 4usize],
}
impl Default for _mbstate_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _mbstate_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type __nlink_t = ::libc::c_ushort;
pub type __suseconds_t = ::libc::c_long;
pub type __ULong = ::libc::c_ulong;
pub type _LOCK_T = i32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct __lock_t {
    pub lock: _LOCK_T,
    pub thread_tag: u32,
    pub counter: u32,
}
pub type _LOCK_RECURSIVE_T = __lock_t;
pub type _flock_t = _LOCK_RECURSIVE_T;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __locale_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Bigint {
    pub _next: *mut _Bigint,
    pub _k: ::libc::c_int,
    pub _maxwds: ::libc::c_int,
    pub _sign: ::libc::c_int,
    pub _wds: ::libc::c_int,
    pub _x: [__ULong; 1usize],
}
impl Default for _Bigint {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct __tm {
    pub __tm_sec: ::libc::c_int,
    pub __tm_min: ::libc::c_int,
    pub __tm_hour: ::libc::c_int,
    pub __tm_mday: ::libc::c_int,
    pub __tm_mon: ::libc::c_int,
    pub __tm_year: ::libc::c_int,
    pub __tm_wday: ::libc::c_int,
    pub __tm_yday: ::libc::c_int,
    pub __tm_isdst: ::libc::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _on_exit_args {
    pub _fnargs: [*mut ::libc::c_void; 32usize],
    pub _dso_handle: [*mut ::libc::c_void; 32usize],
    pub _fntypes: __ULong,
    pub _is_cxa: __ULong,
}
impl Default for _on_exit_args {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _atexit {
    pub _next: *mut _atexit,
    pub _ind: ::libc::c_int,
    pub _fns: [::core::option::Option<unsafe extern "C" fn()>; 32usize],
    pub _on_exit_args: _on_exit_args,
}
impl Default for _atexit {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sbuf {
    pub _base: *mut ::libc::c_uchar,
    pub _size: ::libc::c_int,
}
impl Default for __sbuf {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __sFILE {
    pub _p: *mut ::libc::c_uchar,
    pub _r: ::libc::c_int,
    pub _w: ::libc::c_int,
    pub _flags: ::libc::c_short,
    pub _file: ::libc::c_short,
    pub _bf: __sbuf,
    pub _lbfsize: ::libc::c_int,
    pub _cookie: *mut ::libc::c_void,
    pub _read: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut _reent,
            arg2: *mut ::libc::c_void,
            arg3: *mut ::libc::c_char,
            arg4: ::libc::c_int,
        ) -> ::libc::c_int,
    >,
    pub _write: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut _reent,
            arg2: *mut ::libc::c_void,
            arg3: *const ::libc::c_char,
            arg4: ::libc::c_int,
        ) -> ::libc::c_int,
    >,
    pub _seek: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut _reent,
            arg2: *mut ::libc::c_void,
            arg3: _fpos_t,
            arg4: ::libc::c_int,
        ) -> _fpos_t,
    >,
    pub _close: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut _reent, arg2: *mut ::libc::c_void) -> ::libc::c_int,
    >,
    pub _ub: __sbuf,
    pub _up: *mut ::libc::c_uchar,
    pub _ur: ::libc::c_int,
    pub _ubuf: [::libc::c_uchar; 3usize],
    pub _nbuf: [::libc::c_uchar; 1usize],
    pub _lb: __sbuf,
    pub _blksize: ::libc::c_int,
    pub _offset: _off_t,
    pub _data: *mut _reent,
    pub _lock: _flock_t,
    pub _mbstate: _mbstate_t,
    pub _flags2: ::libc::c_int,
}
impl Default for __sFILE {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type __FILE = __sFILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _glue {
    pub _next: *mut _glue,
    pub _niobs: ::libc::c_int,
    pub _iobs: *mut __FILE,
}
impl Default for _glue {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _rand48 {
    pub _seed: [::libc::c_ushort; 3usize],
    pub _mult: [::libc::c_ushort; 3usize],
    pub _add: ::libc::c_ushort,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _reent {
    pub _errno: ::libc::c_int,
    pub _stdin: *mut __FILE,
    pub _stdout: *mut __FILE,
    pub _stderr: *mut __FILE,
    pub _inc: ::libc::c_int,
    pub _emergency: [::libc::c_char; 25usize],
    pub _unspecified_locale_info: ::libc::c_int,
    pub _locale: *mut __locale_t,
    pub __sdidinit: ::libc::c_int,
    pub __cleanup: ::core::option::Option<unsafe extern "C" fn(arg1: *mut _reent)>,
    pub _result: *mut _Bigint,
    pub _result_k: ::libc::c_int,
    pub _p5s: *mut _Bigint,
    pub _freelist: *mut *mut _Bigint,
    pub _cvtlen: ::libc::c_int,
    pub _cvtbuf: *mut ::libc::c_char,
    pub _new: _reent__bindgen_ty_1,
    pub _atexit: *mut _atexit,
    pub _atexit0: _atexit,
    pub _sig_func: *mut ::core::option::Option<unsafe extern "C" fn(arg1: ::libc::c_int)>,
    pub __sglue: _glue,
    pub __sf: [__FILE; 3usize],
    pub deviceData: *mut ::libc::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _reent__bindgen_ty_1 {
    pub _reent: _reent__bindgen_ty_1__bindgen_ty_1,
    pub _unused: _reent__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _reent__bindgen_ty_1__bindgen_ty_1 {
    pub _unused_rand: ::libc::c_uint,
    pub _strtok_last: *mut ::libc::c_char,
    pub _asctime_buf: [::libc::c_char; 26usize],
    pub _localtime_buf: __tm,
    pub _gamma_signgam: ::libc::c_int,
    pub _rand_next: ::libc::c_ulonglong,
    pub _r48: _rand48,
    pub _mblen_state: _mbstate_t,
    pub _mbtowc_state: _mbstate_t,
    pub _wctomb_state: _mbstate_t,
    pub _l64a_buf: [::libc::c_char; 8usize],
    pub _signal_buf: [::libc::c_char; 24usize],
    pub _getdate_err: ::libc::c_int,
    pub _mbrlen_state: _mbstate_t,
    pub _mbrtowc_state: _mbstate_t,
    pub _mbsrtowcs_state: _mbstate_t,
    pub _wcrtomb_state: _mbstate_t,
    pub _wcsrtombs_state: _mbstate_t,
    pub _h_errno: ::libc::c_int,
}
impl Default for _reent__bindgen_ty_1__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _reent__bindgen_ty_1__bindgen_ty_2 {
    pub _nextf: [*mut ::libc::c_uchar; 30usize],
    pub _nmalloc: [::libc::c_uint; 30usize],
}
impl Default for _reent__bindgen_ty_1__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _reent__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _reent {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type suseconds_t = __suseconds_t;
pub type time_t = __int_least64_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct timeval {
    pub tv_sec: time_t,
    pub tv_usec: suseconds_t,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::libc::c_long,
}
pub type blkcnt_t = __blkcnt_t;
pub type blksize_t = __blksize_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
pub type ino_t = __ino_t;
pub type off_t = __off_t;
pub type dev_t = __dev_t;
pub type uid_t = __uid_t;
pub type gid_t = __gid_t;
pub type ssize_t = _ssize_t;
pub type mode_t = __mode_t;
pub type nlink_t = __nlink_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct stat {
    pub st_dev: dev_t,
    pub st_ino: ino_t,
    pub st_mode: mode_t,
    pub st_nlink: nlink_t,
    pub st_uid: uid_t,
    pub st_gid: gid_t,
    pub st_rdev: dev_t,
    pub st_size: off_t,
    pub st_atim: timespec,
    pub st_mtim: timespec,
    pub st_ctim: timespec,
    pub st_blksize: blksize_t,
    pub st_blocks: blkcnt_t,
    pub st_spare4: [::libc::c_long; 2usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct statvfs {
    pub f_bsize: ::libc::c_ulong,
    pub f_frsize: ::libc::c_ulong,
    pub f_blocks: fsblkcnt_t,
    pub f_bfree: fsblkcnt_t,
    pub f_bavail: fsblkcnt_t,
    pub f_files: fsfilcnt_t,
    pub f_ffree: fsfilcnt_t,
    pub f_favail: fsfilcnt_t,
    pub f_fsid: ::libc::c_ulong,
    pub f_flag: ::libc::c_ulong,
    pub f_namemax: ::libc::c_ulong,
}
pub const STD_IN: ::libc::c_uint = 0;
pub const STD_OUT: ::libc::c_uint = 1;
pub const STD_ERR: ::libc::c_uint = 2;
pub const STD_MAX: ::libc::c_uint = 35;
pub type _bindgen_ty_1 = ::libc::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DIR_ITER {
    pub device: ::libc::c_int,
    pub dirStruct: *mut ::libc::c_void,
}
impl Default for DIR_ITER {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct devoptab_t {
    pub name: *const ::libc::c_char,
    pub structSize: size_t,
    pub open_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            fileStruct: *mut ::libc::c_void,
            path: *const ::libc::c_char,
            flags: ::libc::c_int,
            mode: ::libc::c_int,
        ) -> ::libc::c_int,
    >,
    pub close_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, fd: *mut ::libc::c_void) -> ::libc::c_int,
    >,
    pub write_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            fd: *mut ::libc::c_void,
            ptr: *const ::libc::c_char,
            len: size_t,
        ) -> ssize_t,
    >,
    pub read_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            fd: *mut ::libc::c_void,
            ptr: *mut ::libc::c_char,
            len: size_t,
        ) -> ssize_t,
    >,
    pub seek_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            fd: *mut ::libc::c_void,
            pos: off_t,
            dir: ::libc::c_int,
        ) -> off_t,
    >,
    pub fstat_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            fd: *mut ::libc::c_void,
            st: *mut stat,
        ) -> ::libc::c_int,
    >,
    pub stat_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            file: *const ::libc::c_char,
            st: *mut stat,
        ) -> ::libc::c_int,
    >,
    pub link_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            existing: *const ::libc::c_char,
            newLink: *const ::libc::c_char,
        ) -> ::libc::c_int,
    >,
    pub unlink_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, name: *const ::libc::c_char) -> ::libc::c_int,
    >,
    pub chdir_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, name: *const ::libc::c_char) -> ::libc::c_int,
    >,
    pub rename_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            oldName: *const ::libc::c_char,
            newName: *const ::libc::c_char,
        ) -> ::libc::c_int,
    >,
    pub mkdir_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            path: *const ::libc::c_char,
            mode: ::libc::c_int,
        ) -> ::libc::c_int,
    >,
    pub dirStateSize: size_t,
    pub diropen_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            dirState: *mut DIR_ITER,
            path: *const ::libc::c_char,
        ) -> *mut DIR_ITER,
    >,
    pub dirreset_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, dirState: *mut DIR_ITER) -> ::libc::c_int,
    >,
    pub dirnext_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            dirState: *mut DIR_ITER,
            filename: *mut ::libc::c_char,
            filestat: *mut stat,
        ) -> ::libc::c_int,
    >,
    pub dirclose_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, dirState: *mut DIR_ITER) -> ::libc::c_int,
    >,
    pub statvfs_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            path: *const ::libc::c_char,
            buf: *mut statvfs,
        ) -> ::libc::c_int,
    >,
    pub ftruncate_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, fd: *mut ::libc::c_void, len: off_t) -> ::libc::c_int,
    >,
    pub fsync_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, fd: *mut ::libc::c_void) -> ::libc::c_int,
    >,
    pub deviceData: *mut ::libc::c_void,
    pub chmod_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            path: *const ::libc::c_char,
            mode: mode_t,
        ) -> ::libc::c_int,
    >,
    pub fchmod_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            fd: *mut ::libc::c_void,
            mode: mode_t,
        ) -> ::libc::c_int,
    >,
    pub rmdir_r: ::core::option::Option<
        unsafe extern "C" fn(r: *mut _reent, name: *const ::libc::c_char) -> ::libc::c_int,
    >,
    pub lstat_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            file: *const ::libc::c_char,
            st: *mut stat,
        ) -> ::libc::c_int,
    >,
    pub utimes_r: ::core::option::Option<
        unsafe extern "C" fn(
            r: *mut _reent,
            filename: *const ::libc::c_char,
            times: *const timeval,
        ) -> ::libc::c_int,
    >,
}
impl Default for devoptab_t {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
